export const REGISTRATION_LOADING = 'REGISTRATION_LOADING';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const OTP_LOADING = 'OTP_LOADING';
export const OTP_FAILED = 'OTP_FAILED';
export const OTP_SUCCESS = 'OTP_SUCCESS';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const RESEND_OTP_LOADING = 'RESEND_OTP_LOADING';
export const RESEND_OTP_FAILED = 'RESEND_OTP_FAILED';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';




export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';


export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';


export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';


export const UPDATE_BUSINESS_LOADING = 'UPDATE_BUSINESS_LOADING';
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
export const UPDATE_BUSINESS_FAILED = 'UPDATE_BUSINESS_FAILED';


export const GET_ALL_INDUSTRY_LOADING = 'GET_ALL_INDUSTRY_LOADING';
export const GET_ALL_INDUSTRY_FAILED = 'GET_ALL_INDUSTRY_FAILED';
export const GET_ALL_INDUSTRY_SUCCESS = 'GET_ALL_INDUSTRY_SUCCESS';

export const GET_ALL_TRANSACTION_LOADING = 'GET_ALL_TRANSACTION_LOADING';
export const GET_ALL_TRANSACTION_FAILED = 'GET_ALL_TRANSACTION_FAILED';
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';


export const GET_ALL_WALLET_REPORT_LOADING = 'GET_ALL_WALLET_REPORT_LOADING';
export const GET_ALL_WALLET_REPORT_FAILED = 'GET_ALL_WALLET_REPORT_FAILED';
export const GET_ALL_WALLET_REPORT_SUCCESS = 'GET_ALL_WALLET_TRANSANCTION_SUCCESS';


export const GET_ALL_WITHDRAW_LOADING = 'GET_ALL_WITHDRAW_LOADING';
export const GET_ALL_WITHDRAW_FAILED = 'GET_ALL_WITHDRAW_FAILED';
export const GET_ALL_WITHDRAW_SUCCESS = 'GET_ALL_WITHDRAW_SUCCESS';

export const MAKE_WITHDRAW_LOADING = 'MAKE_WITHDRAW_LOADING';
export const MAKE_WITHDRAW_FAILED = 'MAKE_WITHDRAW_FAILED';
export const MAKE_WITHDRAW_SUCCESS = 'GET_ALL_WITHDRAW_SUCCESS';

export const MAKE_REQEUST_LOADING = 'MAKE_REQEUST_LOADING';
export const MAKE_REQEUST_FAILED = 'MAKE_REQEUST_FAILED';
export const MAKE_REQEUST_SUCCESS = 'MAKE_REQUEST_SUCCESS';

export const GET_ALL_PAYMENT_LOADING = 'GET_ALL_PAYMENT_LOADING';
export const GET_ALL_PAYMENT_FAILED  = 'GET_ALL_PAYMENT_FAILED ';
export const GET_ALL_PAYMENT_SUCCESS= 'GET_ALL_PAYMENT_SUCCESS';


export const GET_ALL_PRODUCT_CATEGORY_LOADING = 'GET_ALL_PRODUCT_CATEGORY_LOADING';
export const GET_ALL_PRODUCT_CATEGORY_SUCCESS = 'GET_ALL_PRODUCT_CATEGORY_SUCCESS';
export const GET_ALL_PRODUCT_CATEGORY_FAILED = 'GET_ALL_PRODUCT_CATEGORY_FAILED';


export const GET_ALL_PRODUCT_LOADING = 'GET_ALL_PRODUCT_LOADING';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED';

export const GET_ALL_PRODUCT_BY_PAGINATION_LOADING = 'GET_ALL_PRODUCT_BY_PAGINATION_LOADING';
export const GET_ALL_PRODUCT_BY_PAGINATION_SUCCESS = 'GET_ALL_PRODUCT_BY_PAGINATION_SUCCESS';
export const GET_ALL_PRODUCT_BY_PAGINATION_FAILED = 'GET_ALL_PRODUCT_BY_PAGINATION_FAILED';


export const GET_SINGLE_PRODUCT_LOADING = 'GET_SINGLE_PRODUCT_LOADING';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILED = 'GET_SINGLE_PRODUCT_FAILED';


export const MAKE_FEATURED_PRODUCT_LOADING = 'MAKE_FEATURED_PRODUCT_LOADING';
export const MAKE_FEATURED_PRODUCT_SUCCESS = 'MAKE_FEATURED_PRODUCT_SUCCESS';
export const MAKE_FEATURED_PRODUCT_FAILED = 'MAKE_FEATURED_PRODUCT_FAILED';


export const GET_PAYMENT_OPTION_LOADING = 'GET_PAYMENT_OPTION_LOADING';
export const GET_PAYMENT_OPTION_SUCCESS = 'GET_PAYMENT_OPTION_SUCCESS';
export const GET_PAYMENT_OPTION_FAILED = 'GET_PAYMENT_OPTION_FAILED';


export const SET_PAYMENT_OPTION_LOADING = 'SET_PAYMENT_OPTION_LOADING';
export const SET_PAYMENT_OPTION_SUCCESS = 'SET_PAYMENT_OPTION_SUCCESS';
export const SET_PAYMENT_OPTION_FAILED = 'SET_PAYMENT_OPTION_FAILED';




export const CREATE_STORE_LOADING = 'CREATE_STORE_LOADING';
export const CREATE_STORE_FAILED = 'CREATE_STORE_FAILED';
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';

export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';

export const SEARCH_PRODUCT_LOADING = 'SEARCH_PRODUCT_LOADING';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILED = 'SEARCH_PRODUCT_FAILED';



export const UPDATE_BANK_LOADING = 'UPDATE_BANK_LOADING';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_FAILED = 'UPDATE_BANK_FAILED';

export const GET_BANK_USER_DETAILS_LOADING = 'GET_BANK_USER_DETAILS_LOADING';
export const GET_BANK_USER_DETAILS_SUCCESS = 'GET_BANK_USER_DETAILS_SUCCESS';
export const GET_BANK_USER_DETAILS_FAILED = 'GET_BANK_USER_DETAILS_FAILED';



export const GET_ALL_BANK_LOADING = 'GET_ALL_BANK_LOADING';
export const GET_ALL_BANK_SUCCESS = 'GET_ALL_BANK_SUCCESS';
export const GET_ALL_BANK_FAILED = 'GET_ALL_BANK_FAILED';


export const GET_ALL_DISPUTE_LOADING = 'GET_ALL_DISPUTE_LOADING';
export const GET_ALL_DISPUTE_SUCCESS = 'GET_ALL_DISPUTE_SUCCESS';
export const GET_ALL_DISPUTE_FAILED = 'GET_ALL_DISPUTE_FAILED';



export const GET_DISPUTE_ID_LOADING = 'GET_DISPUTE_ID_LOADING';
export const GET_DISPUTE_ID_SUCCESS = 'GET_DISPUTE_ID_SUCCESS';
export const GET_DISPUTE_ID_FAILED = 'GET_DISPUTE_ID_FAILED';


